--- 

- name: Add Nginx stable repo
  apt_repository: repo=ppa:nginx/stable
  # apt_repository: repo=ppa:nginx/development

- name: update apt repo
  apt: update-cache=yes

- name: install nginx 
  apt: name=nginx state=installed

- name: service nginx 
  service: name=nginx state=started 

- name: write nginx.conf 
  template: src=nginx.conf.j2 
            dest=/etc/nginx/nginx.conf 
            backup=yes
  notify:
    - restart nginx

- name: create directory {{ website_root }}
  file: dest={{ website_root }}
        state=directory
